const COUNTRIES = [
  { name: "Afghanistan", iso2: "af", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albania", iso2: "al", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", iso2: "dz", dialCode: "+213", flag: "🇩🇿" },
  { name: "American Samoa", iso2: "as", dialCode: "+1684", flag: "🇦🇸" },
  { name: "Andorra", iso2: "ad", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", iso2: "ao", dialCode: "+244", flag: "🇦🇴" },
  { name: "Argentina", iso2: "ar", dialCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", iso2: "am", dialCode: "+374", flag: "🇦🇲" },
  { name: "Australia", iso2: "au", dialCode: "+61", flag: "🇦🇺" },
  { name: "Austria", iso2: "at", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", iso2: "az", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahrain", iso2: "bh", dialCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", iso2: "bd", dialCode: "+880", flag: "🇧🇩" },
  { name: "Belarus", iso2: "by", dialCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", iso2: "be", dialCode: "+32", flag: "🇧🇪" },
  { name: "Bolivia", iso2: "bo", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", iso2: "ba", dialCode: "+387", flag: "🇧🇦" },
  { name: "Brazil", iso2: "br", dialCode: "+55", flag: "🇧🇷" },
  { name: "Bulgaria", iso2: "bg", dialCode: "+359", flag: "🇧🇬" },
  { name: "Cambodia", iso2: "kh", dialCode: "+855", flag: "🇰🇭" },
  { name: "Cameroon", iso2: "cm", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", iso2: "ca", dialCode: "+1", flag: "🇨🇦" },
  { name: "Chile", iso2: "cl", dialCode: "+56", flag: "🇨🇱" },
  { name: "China", iso2: "cn", dialCode: "+86", flag: "🇨🇳" },
  { name: "Colombia", iso2: "co", dialCode: "+57", flag: "🇨🇴" },
  { name: "Costa Rica", iso2: "cr", dialCode: "+506", flag: "🇨🇷" },
  { name: "Croatia", iso2: "hr", dialCode: "+385", flag: "🇭🇷" },
  { name: "Czechia", iso2: "cz", dialCode: "+420", flag: "🇨🇿" },
  { name: "Denmark", iso2: "dk", dialCode: "+45", flag: "🇩🇰" },
  { name: "Dominican Republic", iso2: "do", dialCode: "+1", flag: "🇩🇴" },
  { name: "Ecuador", iso2: "ec", dialCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", iso2: "eg", dialCode: "+20", flag: "🇪🇬" },
  { name: "Estonia", iso2: "ee", dialCode: "+372", flag: "🇪🇪" },
  { name: "Finland", iso2: "fi", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", iso2: "fr", dialCode: "+33", flag: "🇫🇷" },
  { name: "Germany", iso2: "de", dialCode: "+49", flag: "🇩🇪" },
  { name: "Ghana", iso2: "gh", dialCode: "+233", flag: "🇬🇭" },
  { name: "Greece", iso2: "gr", dialCode: "+30", flag: "🇬🇷" },
  { name: "Hong Kong", iso2: "hk", dialCode: "+852", flag: "🇭🇰" },
  { name: "Hungary", iso2: "hu", dialCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", iso2: "is", dialCode: "+354", flag: "🇮🇸" },
  { name: "India", iso2: "in", dialCode: "+91", flag: "🇮🇳" },
  { name: "Indonesia", iso2: "id", dialCode: "+62", flag: "🇮🇩" },
  { name: "Iran", iso2: "ir", dialCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", iso2: "iq", dialCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", iso2: "ie", dialCode: "+353", flag: "🇮🇪" },
  { name: "Israel", iso2: "il", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italy", iso2: "it", dialCode: "+39", flag: "🇮🇹" },
  { name: "Japan", iso2: "jp", dialCode: "+81", flag: "🇯🇵" },
  { name: "Jordan", iso2: "jo", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kenya", iso2: "ke", dialCode: "+254", flag: "🇰🇪" },
  { name: "Kuwait", iso2: "kw", dialCode: "+965", flag: "🇰🇼" },
  { name: "Latvia", iso2: "lv", dialCode: "+371", flag: "🇱🇻" },
  { name: "Lebanon", iso2: "lb", dialCode: "+961", flag: "🇱🇧" },
  { name: "Lithuania", iso2: "lt", dialCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", iso2: "lu", dialCode: "+352", flag: "🇱🇺" },
  { name: "Malaysia", iso2: "my", dialCode: "+60", flag: "🇲🇾" },
  { name: "Mexico", iso2: "mx", dialCode: "+52", flag: "🇲🇽" },
  { name: "Morocco", iso2: "ma", dialCode: "+212", flag: "🇲🇦" },
  { name: "Nepal", iso2: "np", dialCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", iso2: "nl", dialCode: "+31", flag: "🇳🇱" },
  { name: "New Zealand", iso2: "nz", dialCode: "+64", flag: "🇳🇿" },
  { name: "Nigeria", iso2: "ng", dialCode: "+234", flag: "🇳🇬" },
  { name: "Norway", iso2: "no", dialCode: "+47", flag: "🇳🇴" },
  { name: "Oman", iso2: "om", dialCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", iso2: "pk", dialCode: "+92", flag: "🇵🇰" },
  { name: "Panama", iso2: "pa", dialCode: "+507", flag: "🇵🇦" },
  { name: "Peru", iso2: "pe", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", iso2: "ph", dialCode: "+63", flag: "🇵🇭" },
  { name: "Poland", iso2: "pl", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", iso2: "pt", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", iso2: "qa", dialCode: "+974", flag: "🇶🇦" },
  { name: "Romania", iso2: "ro", dialCode: "+40", flag: "🇷🇴" },
  { name: "Russia", iso2: "ru", dialCode: "+7", flag: "🇷🇺" },
  { name: "Saudi Arabia", iso2: "sa", dialCode: "+966", flag: "🇸🇦" },
  { name: "Serbia", iso2: "rs", dialCode: "+381", flag: "🇷🇸" },
  { name: "Singapore", iso2: "sg", dialCode: "+65", flag: "🇸🇬" },
  { name: "South Africa", iso2: "za", dialCode: "+27", flag: "🇿🇦" },
  { name: "South Korea", iso2: "kr", dialCode: "+82", flag: "🇰🇷" },
  { name: "Spain", iso2: "es", dialCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", iso2: "lk", dialCode: "+94", flag: "🇱🇰" },
  { name: "Sweden", iso2: "se", dialCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", iso2: "ch", dialCode: "+41", flag: "🇨🇭" },
  { name: "Taiwan", iso2: "tw", dialCode: "+886", flag: "🇹🇼" },
  { name: "Thailand", iso2: "th", dialCode: "+66", flag: "🇹🇭" },
  { name: "Turkey", iso2: "tr", dialCode: "+90", flag: "🇹🇷" },
  { name: "United Arab Emirates", iso2: "ae", dialCode: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", iso2: "gb", dialCode: "+44", flag: "🇬🇧" },
  { name: "United States", iso2: "us", dialCode: "+1", flag: "🇺🇸" },
  { name: "Uruguay", iso2: "uy", dialCode: "+598", flag: "🇺🇾" },
  { name: "Venezuela", iso2: "ve", dialCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", iso2: "vn", dialCode: "+84", flag: "🇻🇳" },
];

export default COUNTRIES;
